// Copyright (C) 2025 Brian Curnow
//
// This file is part of zonemgr.
//
// zonemgr is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// zonemgr is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with zonemgr.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: plugins/proto/zonemgrplugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define the various schema objects
type Config struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	GenerateSerial             bool                   `protobuf:"varint,1,opt,name=generate_serial,json=generateSerial,proto3" json:"generate_serial,omitempty"`
	SerialChangeIndex          uint32                 `protobuf:"varint,2,opt,name=serial_change_index,json=serialChangeIndex,proto3" json:"serial_change_index,omitempty"`
	GenerateReverseLookupZones bool                   `protobuf:"varint,3,opt,name=generate_reverse_lookup_zones,json=generateReverseLookupZones,proto3" json:"generate_reverse_lookup_zones,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_plugins_proto_zonemgrplugin_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetGenerateSerial() bool {
	if x != nil {
		return x.GenerateSerial
	}
	return false
}

func (x *Config) GetSerialChangeIndex() uint32 {
	if x != nil {
		return x.SerialChangeIndex
	}
	return 0
}

func (x *Config) GetGenerateReverseLookupZones() bool {
	if x != nil {
		return x.GenerateReverseLookupZones
	}
	return false
}

type ResourceRecordValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRecordValue) Reset() {
	*x = ResourceRecordValue{}
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRecordValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRecordValue) ProtoMessage() {}

func (x *ResourceRecordValue) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRecordValue.ProtoReflect.Descriptor instead.
func (*ResourceRecordValue) Descriptor() ([]byte, []int) {
	return file_plugins_proto_zonemgrplugin_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceRecordValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ResourceRecordValue) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type ResourceRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Class         string                 `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	Ttl           int32                  `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Values        []*ResourceRecordValue `protobuf:"bytes,5,rep,name=values,proto3" json:"values,omitempty"`
	Value         string                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	Comment       string                 `protobuf:"bytes,7,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRecord) Reset() {
	*x = ResourceRecord{}
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRecord) ProtoMessage() {}

func (x *ResourceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRecord.ProtoReflect.Descriptor instead.
func (*ResourceRecord) Descriptor() ([]byte, []int) {
	return file_plugins_proto_zonemgrplugin_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceRecord) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *ResourceRecord) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *ResourceRecord) GetValues() []*ResourceRecordValue {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ResourceRecord) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ResourceRecord) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type TTL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ttl           int32                  `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTL) Reset() {
	*x = TTL{}
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTL) ProtoMessage() {}

func (x *TTL) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTL.ProtoReflect.Descriptor instead.
func (*TTL) Descriptor() ([]byte, []int) {
	return file_plugins_proto_zonemgrplugin_proto_rawDescGZIP(), []int{3}
}

func (x *TTL) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *TTL) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type Zone struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	Config          *Config                    `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ResourceRecords map[string]*ResourceRecord `protobuf:"bytes,2,rep,name=resource_records,json=resourceRecords,proto3" json:"resource_records,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ttl             *TTL                       `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Zone) Reset() {
	*x = Zone{}
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_plugins_proto_zonemgrplugin_proto_rawDescGZIP(), []int{4}
}

func (x *Zone) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Zone) GetResourceRecords() map[string]*ResourceRecord {
	if x != nil {
		return x.ResourceRecords
	}
	return nil
}

func (x *Zone) GetTtl() *TTL {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugins_proto_zonemgrplugin_proto_rawDescGZIP(), []int{5}
}

type PluginVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginVersionResponse) Reset() {
	*x = PluginVersionResponse{}
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginVersionResponse) ProtoMessage() {}

func (x *PluginVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginVersionResponse.ProtoReflect.Descriptor instead.
func (*PluginVersionResponse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_zonemgrplugin_proto_rawDescGZIP(), []int{6}
}

func (x *PluginVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PluginTypesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SupportedTypes []string               `protobuf:"bytes,1,rep,name=supportedTypes,proto3" json:"supportedTypes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PluginTypesResponse) Reset() {
	*x = PluginTypesResponse{}
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginTypesResponse) ProtoMessage() {}

func (x *PluginTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginTypesResponse.ProtoReflect.Descriptor instead.
func (*PluginTypesResponse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_zonemgrplugin_proto_rawDescGZIP(), []int{7}
}

func (x *PluginTypesResponse) GetSupportedTypes() []string {
	if x != nil {
		return x.SupportedTypes
	}
	return nil
}

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_zonemgrplugin_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigureRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type NormalizeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identifier     string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	ResourceRecord *ResourceRecord        `protobuf:"bytes,2,opt,name=resource_record,json=resourceRecord,proto3" json:"resource_record,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NormalizeRequest) Reset() {
	*x = NormalizeRequest{}
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizeRequest) ProtoMessage() {}

func (x *NormalizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizeRequest.ProtoReflect.Descriptor instead.
func (*NormalizeRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_zonemgrplugin_proto_rawDescGZIP(), []int{9}
}

func (x *NormalizeRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *NormalizeRequest) GetResourceRecord() *ResourceRecord {
	if x != nil {
		return x.ResourceRecord
	}
	return nil
}

type NormalizeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResourceRecord *ResourceRecord        `protobuf:"bytes,1,opt,name=resource_record,json=resourceRecord,proto3" json:"resource_record,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NormalizeResponse) Reset() {
	*x = NormalizeResponse{}
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizeResponse) ProtoMessage() {}

func (x *NormalizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizeResponse.ProtoReflect.Descriptor instead.
func (*NormalizeResponse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_zonemgrplugin_proto_rawDescGZIP(), []int{10}
}

func (x *NormalizeResponse) GetResourceRecord() *ResourceRecord {
	if x != nil {
		return x.ResourceRecord
	}
	return nil
}

type ValidateZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Zone          *Zone                  `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateZoneRequest) Reset() {
	*x = ValidateZoneRequest{}
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateZoneRequest) ProtoMessage() {}

func (x *ValidateZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateZoneRequest.ProtoReflect.Descriptor instead.
func (*ValidateZoneRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_zonemgrplugin_proto_rawDescGZIP(), []int{11}
}

func (x *ValidateZoneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ValidateZoneRequest) GetZone() *Zone {
	if x != nil {
		return x.Zone
	}
	return nil
}

type RenderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identifier     string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	ResourceRecord *ResourceRecord        `protobuf:"bytes,2,opt,name=resource_record,json=resourceRecord,proto3" json:"resource_record,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_zonemgrplugin_proto_rawDescGZIP(), []int{12}
}

func (x *RenderRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *RenderRequest) GetResourceRecord() *ResourceRecord {
	if x != nil {
		return x.ResourceRecord
	}
	return nil
}

type RenderResonse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderResonse) Reset() {
	*x = RenderResonse{}
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderResonse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderResonse) ProtoMessage() {}

func (x *RenderResonse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_zonemgrplugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderResonse.ProtoReflect.Descriptor instead.
func (*RenderResonse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_zonemgrplugin_proto_rawDescGZIP(), []int{13}
}

func (x *RenderResonse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_plugins_proto_zonemgrplugin_proto protoreflect.FileDescriptor

const file_plugins_proto_zonemgrplugin_proto_rawDesc = "" +
	"\n" +
	"!plugins/proto/zonemgrplugin.proto\"\xa4\x01\n" +
	"\x06Config\x12'\n" +
	"\x0fgenerate_serial\x18\x01 \x01(\bR\x0egenerateSerial\x12.\n" +
	"\x13serial_change_index\x18\x02 \x01(\rR\x11serialChangeIndex\x12A\n" +
	"\x1dgenerate_reverse_lookup_zones\x18\x03 \x01(\bR\x1agenerateReverseLookupZones\"E\n" +
	"\x13ResourceRecordValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\"\xbe\x01\n" +
	"\x0eResourceRecord\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\x05R\x03ttl\x12,\n" +
	"\x06values\x18\x05 \x03(\v2\x14.ResourceRecordValueR\x06values\x12\x14\n" +
	"\x05value\x18\x06 \x01(\tR\x05value\x12\x18\n" +
	"\acomment\x18\a \x01(\tR\acomment\"1\n" +
	"\x03TTL\x12\x10\n" +
	"\x03ttl\x18\x01 \x01(\x05R\x03ttl\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\"\xdb\x01\n" +
	"\x04Zone\x12\x1f\n" +
	"\x06config\x18\x01 \x01(\v2\a.ConfigR\x06config\x12E\n" +
	"\x10resource_records\x18\x02 \x03(\v2\x1a.Zone.ResourceRecordsEntryR\x0fresourceRecords\x12\x16\n" +
	"\x03ttl\x18\x03 \x01(\v2\x04.TTLR\x03ttl\x1aS\n" +
	"\x14ResourceRecordsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.ResourceRecordR\x05value:\x028\x01\"\a\n" +
	"\x05Empty\"1\n" +
	"\x15PluginVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"=\n" +
	"\x13PluginTypesResponse\x12&\n" +
	"\x0esupportedTypes\x18\x01 \x03(\tR\x0esupportedTypes\"3\n" +
	"\x10ConfigureRequest\x12\x1f\n" +
	"\x06config\x18\x01 \x01(\v2\a.ConfigR\x06config\"l\n" +
	"\x10NormalizeRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x128\n" +
	"\x0fresource_record\x18\x02 \x01(\v2\x0f.ResourceRecordR\x0eresourceRecord\"M\n" +
	"\x11NormalizeResponse\x128\n" +
	"\x0fresource_record\x18\x01 \x01(\v2\x0f.ResourceRecordR\x0eresourceRecord\"D\n" +
	"\x13ValidateZoneRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x04zone\x18\x02 \x01(\v2\x05.ZoneR\x04zone\"i\n" +
	"\rRenderRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x128\n" +
	"\x0fresource_record\x18\x02 \x01(\v2\x0f.ResourceRecordR\x0eresourceRecord\")\n" +
	"\rRenderResonse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent2\xa1\x02\n" +
	"\rZonemgrPlugin\x12/\n" +
	"\rPluginVersion\x12\x06.Empty\x1a\x16.PluginVersionResponse\x12+\n" +
	"\vPluginTypes\x12\x06.Empty\x1a\x14.PluginTypesResponse\x12&\n" +
	"\tConfigure\x12\x11.ConfigureRequest\x1a\x06.Empty\x122\n" +
	"\tNormalize\x12\x11.NormalizeRequest\x1a\x12.NormalizeResponse\x12,\n" +
	"\fValidateZone\x12\x14.ValidateZoneRequest\x1a\x06.Empty\x12(\n" +
	"\x06Render\x12\x0e.RenderRequest\x1a\x0e.RenderResonseB\x11Z\x0f./plugins/protob\x06proto3"

var (
	file_plugins_proto_zonemgrplugin_proto_rawDescOnce sync.Once
	file_plugins_proto_zonemgrplugin_proto_rawDescData []byte
)

func file_plugins_proto_zonemgrplugin_proto_rawDescGZIP() []byte {
	file_plugins_proto_zonemgrplugin_proto_rawDescOnce.Do(func() {
		file_plugins_proto_zonemgrplugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugins_proto_zonemgrplugin_proto_rawDesc), len(file_plugins_proto_zonemgrplugin_proto_rawDesc)))
	})
	return file_plugins_proto_zonemgrplugin_proto_rawDescData
}

var file_plugins_proto_zonemgrplugin_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_plugins_proto_zonemgrplugin_proto_goTypes = []any{
	(*Config)(nil),                // 0: Config
	(*ResourceRecordValue)(nil),   // 1: ResourceRecordValue
	(*ResourceRecord)(nil),        // 2: ResourceRecord
	(*TTL)(nil),                   // 3: TTL
	(*Zone)(nil),                  // 4: Zone
	(*Empty)(nil),                 // 5: Empty
	(*PluginVersionResponse)(nil), // 6: PluginVersionResponse
	(*PluginTypesResponse)(nil),   // 7: PluginTypesResponse
	(*ConfigureRequest)(nil),      // 8: ConfigureRequest
	(*NormalizeRequest)(nil),      // 9: NormalizeRequest
	(*NormalizeResponse)(nil),     // 10: NormalizeResponse
	(*ValidateZoneRequest)(nil),   // 11: ValidateZoneRequest
	(*RenderRequest)(nil),         // 12: RenderRequest
	(*RenderResonse)(nil),         // 13: RenderResonse
	nil,                           // 14: Zone.ResourceRecordsEntry
}
var file_plugins_proto_zonemgrplugin_proto_depIdxs = []int32{
	1,  // 0: ResourceRecord.values:type_name -> ResourceRecordValue
	0,  // 1: Zone.config:type_name -> Config
	14, // 2: Zone.resource_records:type_name -> Zone.ResourceRecordsEntry
	3,  // 3: Zone.ttl:type_name -> TTL
	0,  // 4: ConfigureRequest.config:type_name -> Config
	2,  // 5: NormalizeRequest.resource_record:type_name -> ResourceRecord
	2,  // 6: NormalizeResponse.resource_record:type_name -> ResourceRecord
	4,  // 7: ValidateZoneRequest.zone:type_name -> Zone
	2,  // 8: RenderRequest.resource_record:type_name -> ResourceRecord
	2,  // 9: Zone.ResourceRecordsEntry.value:type_name -> ResourceRecord
	5,  // 10: ZonemgrPlugin.PluginVersion:input_type -> Empty
	5,  // 11: ZonemgrPlugin.PluginTypes:input_type -> Empty
	8,  // 12: ZonemgrPlugin.Configure:input_type -> ConfigureRequest
	9,  // 13: ZonemgrPlugin.Normalize:input_type -> NormalizeRequest
	11, // 14: ZonemgrPlugin.ValidateZone:input_type -> ValidateZoneRequest
	12, // 15: ZonemgrPlugin.Render:input_type -> RenderRequest
	6,  // 16: ZonemgrPlugin.PluginVersion:output_type -> PluginVersionResponse
	7,  // 17: ZonemgrPlugin.PluginTypes:output_type -> PluginTypesResponse
	5,  // 18: ZonemgrPlugin.Configure:output_type -> Empty
	10, // 19: ZonemgrPlugin.Normalize:output_type -> NormalizeResponse
	5,  // 20: ZonemgrPlugin.ValidateZone:output_type -> Empty
	13, // 21: ZonemgrPlugin.Render:output_type -> RenderResonse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_plugins_proto_zonemgrplugin_proto_init() }
func file_plugins_proto_zonemgrplugin_proto_init() {
	if File_plugins_proto_zonemgrplugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugins_proto_zonemgrplugin_proto_rawDesc), len(file_plugins_proto_zonemgrplugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugins_proto_zonemgrplugin_proto_goTypes,
		DependencyIndexes: file_plugins_proto_zonemgrplugin_proto_depIdxs,
		MessageInfos:      file_plugins_proto_zonemgrplugin_proto_msgTypes,
	}.Build()
	File_plugins_proto_zonemgrplugin_proto = out.File
	file_plugins_proto_zonemgrplugin_proto_goTypes = nil
	file_plugins_proto_zonemgrplugin_proto_depIdxs = nil
}
