builds:
  - env: 
    - CGO_ENABLED=0
    goos: 
      - linux
      - darwin
      - windows
    goarch: 
      - amd64
      - arm64
    goarm: 
      - 6
      - 7
    ldflags: 
      - -s -w -X github.com/bcurnow/zonemgr/cmd.version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    github:
      owner: bcurnow
      repo: misc
      force_token: true
env_files:
  github_token: ~/.config/goreleaser/zonemgr-github-token