version: 2
builds:
  - 
    env: 
    - CGO_ENABLED=0
    goos: 
      - linux
      - darwin
      - windows
    goarch: 
      - amd64
      - arm64
    ldflags: 
      - -s -w -X github.com/bcurnow/zonemgr/utils.version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"
env_files:
  github_token: ~/.config/goreleaser/zonemgr-github-token
archives:
  - formats:
    - binary
    - tar.gz