version: 2
builds:
  - 
    env: 
    - CGO_ENABLED=0
    goos: 
      - linux
    goarch: 
      - amd64
    ldflags: 
      - -s -w -X github.com/bcurnow/zonemgr/version.Version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"
env_files:
  github_token: ~/.config/goreleaser/zonemgr-github-token