// Code generated by MockGen. DO NOT EDIT.
// Source: dns/zone_file_generator.go

// Package dns is a generated GoMock package.
package dns

import (
	reflect "reflect"

	models "github.com/bcurnow/zonemgr/models"
	gomock "go.uber.org/mock/gomock"
)

// MockZoneFileGenerator is a mock of ZoneFileGenerator interface.
type MockZoneFileGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockZoneFileGeneratorMockRecorder
}

// MockZoneFileGeneratorMockRecorder is the mock recorder for MockZoneFileGenerator.
type MockZoneFileGeneratorMockRecorder struct {
	mock *MockZoneFileGenerator
}

// NewMockZoneFileGenerator creates a new mock instance.
func NewMockZoneFileGenerator(ctrl *gomock.Controller) *MockZoneFileGenerator {
	mock := &MockZoneFileGenerator{ctrl: ctrl}
	mock.recorder = &MockZoneFileGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockZoneFileGenerator) EXPECT() *MockZoneFileGeneratorMockRecorder {
	return m.recorder
}

// GenerateZone mocks base method.
func (m *MockZoneFileGenerator) GenerateZone(name string, zone *models.Zone, outputDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateZone", name, zone, outputDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateZone indicates an expected call of GenerateZone.
func (mr *MockZoneFileGeneratorMockRecorder) GenerateZone(name, zone, outputDir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateZone", reflect.TypeOf((*MockZoneFileGenerator)(nil).GenerateZone), name, zone, outputDir)
}
