// Code generated by MockGen. DO NOT EDIT.
// Source: dns/parser.go

// Package dns is a generated GoMock package.
package dns

import (
	reflect "reflect"

	models "github.com/bcurnow/zonemgr/models"
	gomock "go.uber.org/mock/gomock"
)

// MockZoneParser is a mock of ZoneParser interface.
type MockZoneParser struct {
	ctrl     *gomock.Controller
	recorder *MockZoneParserMockRecorder
}

// MockZoneParserMockRecorder is the mock recorder for MockZoneParser.
type MockZoneParserMockRecorder struct {
	mock *MockZoneParser
}

// NewMockZoneParser creates a new mock instance.
func NewMockZoneParser(ctrl *gomock.Controller) *MockZoneParser {
	mock := &MockZoneParser{ctrl: ctrl}
	mock.recorder = &MockZoneParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockZoneParser) EXPECT() *MockZoneParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockZoneParser) Parse(inputFile string) (map[string]*models.Zone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", inputFile)
	ret0, _ := ret[0].(map[string]*models.Zone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockZoneParserMockRecorder) Parse(inputFile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockZoneParser)(nil).Parse), inputFile)
}
