// Code generated by MockGen. DO NOT EDIT.
// Source: dns/catalog_generator.go
//
// Generated by this command:
//
//	mockgen -source=dns/catalog_generator.go -package dns -self_package github.com/bcurnow/zonemgr/dns
//

// Package dns is a generated GoMock package.
package dns

import (
	reflect "reflect"

	models "github.com/bcurnow/zonemgr/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCatalogGenerator is a mock of CatalogGenerator interface.
type MockCatalogGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogGeneratorMockRecorder
	isgomock struct{}
}

// MockCatalogGeneratorMockRecorder is the mock recorder for MockCatalogGenerator.
type MockCatalogGeneratorMockRecorder struct {
	mock *MockCatalogGenerator
}

// NewMockCatalogGenerator creates a new mock instance.
func NewMockCatalogGenerator(ctrl *gomock.Controller) *MockCatalogGenerator {
	mock := &MockCatalogGenerator{ctrl: ctrl}
	mock.recorder = &MockCatalogGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogGenerator) EXPECT() *MockCatalogGeneratorMockRecorder {
	return m.recorder
}

// AddCatalogRecords mocks base method.
func (m *MockCatalogGenerator) AddCatalogRecords(catalogZoneName string, zone *models.Zone, memberZoneNames []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCatalogRecords", catalogZoneName, zone, memberZoneNames)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCatalogRecords indicates an expected call of AddCatalogRecords.
func (mr *MockCatalogGeneratorMockRecorder) AddCatalogRecords(catalogZoneName, zone, memberZoneNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCatalogRecords", reflect.TypeOf((*MockCatalogGenerator)(nil).AddCatalogRecords), catalogZoneName, zone, memberZoneNames)
}
