// Code generated by MockGen. DO NOT EDIT.
// Source: dns/zone_reverser.go

// Package dns is a generated GoMock package.
package dns

import (
	reflect "reflect"

	models "github.com/bcurnow/zonemgr/models"
	gomock "go.uber.org/mock/gomock"
)

// MockZoneReverser is a mock of ZoneReverser interface.
type MockZoneReverser struct {
	ctrl     *gomock.Controller
	recorder *MockZoneReverserMockRecorder
}

// MockZoneReverserMockRecorder is the mock recorder for MockZoneReverser.
type MockZoneReverserMockRecorder struct {
	mock *MockZoneReverser
}

// NewMockZoneReverser creates a new mock instance.
func NewMockZoneReverser(ctrl *gomock.Controller) *MockZoneReverser {
	mock := &MockZoneReverser{ctrl: ctrl}
	mock.recorder = &MockZoneReverserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockZoneReverser) EXPECT() *MockZoneReverserMockRecorder {
	return m.recorder
}

// ReverseZone mocks base method.
func (m *MockZoneReverser) ReverseZone(sourceZoneName string, zone *models.Zone) (map[string]*models.Zone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReverseZone", sourceZoneName, zone)
	ret0, _ := ret[0].(map[string]*models.Zone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReverseZone indicates an expected call of ReverseZone.
func (mr *MockZoneReverserMockRecorder) ReverseZone(sourceZoneName, zone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReverseZone", reflect.TypeOf((*MockZoneReverser)(nil).ReverseZone), sourceZoneName, zone)
}
