// Code generated by MockGen. DO NOT EDIT.
// Source: plugins/plugin_manager.go

// Package plugins is a generated GoMock package.
package plugins

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPluginManager is a mock of PluginManager interface.
type MockPluginManager struct {
	ctrl     *gomock.Controller
	recorder *MockPluginManagerMockRecorder
}

// MockPluginManagerMockRecorder is the mock recorder for MockPluginManager.
type MockPluginManagerMockRecorder struct {
	mock *MockPluginManager
}

// NewMockPluginManager creates a new mock instance.
func NewMockPluginManager(ctrl *gomock.Controller) *MockPluginManager {
	mock := &MockPluginManager{ctrl: ctrl}
	mock.recorder = &MockPluginManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPluginManager) EXPECT() *MockPluginManagerMockRecorder {
	return m.recorder
}

// Plugins mocks base method.
func (m *MockPluginManager) Plugins() (map[PluginType]*Plugin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Plugins")
	ret0, _ := ret[0].(map[PluginType]*Plugin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Plugins indicates an expected call of Plugins.
func (mr *MockPluginManagerMockRecorder) Plugins() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Plugins", reflect.TypeOf((*MockPluginManager)(nil).Plugins))
}
