/**
 * Copyright (C) 2025 Brian Curnow
 *
 * This file is part of zonemgr.
 *
 * zonemgr is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * zonemgr is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with zonemgr.  If not, see <https://www.gnu.org/licenses/>.
 */

package converter

import (
	"github.com/bcurnow/zonemgr/plugins"
	"github.com/bcurnow/zonemgr/schema"
)

const UNKNOWN = "UNKNOWN"

// I dont' really want this package but I need to convert both PluginType to ResourceRecordType and the reverse and that creates an import cycle so here we are
func PluginType(t schema.ResourceRecordType) plugins.PluginType {
	switch t {
	case schema.A:
		return plugins.A
	case schema.A6:
		return plugins.A6
	case schema.AAAA:
		return plugins.AAAA
	case schema.AFSDB:
		return plugins.AFSDB
	case schema.ALIAS:
		return plugins.ALIAS
	case schema.ANAME:
		return plugins.ANAME
	case schema.APL:
		return plugins.APL
	case schema.ATMA:
		return plugins.ATMA
	case schema.AXFR:
		return plugins.AXFR
	case schema.CAA:
		return plugins.CAA
	case schema.CDNSKEY:
		return plugins.CDNSKEY
	case schema.CDS:
		return plugins.CDS
	case schema.CERT:
		return plugins.CERT
	case schema.CNAME:
		return plugins.CNAME
	case schema.CSYNC:
		return plugins.CSYNC
	case schema.DHCID:
		return plugins.DHCID
	case schema.DLV:
		return plugins.DLV
	case schema.DNAME:
		return plugins.DNAME
	case schema.DNSKEY:
		return plugins.DNSKEY
	case schema.DOA:
		return plugins.DOA
	case schema.DS:
		return plugins.DS
	case schema.EID:
		return plugins.EID
	case schema.EUI48:
		return plugins.EUI48
	case schema.EUI64:
		return plugins.EUI64
	case schema.GID:
		return plugins.GID
	case schema.GPOS:
		return plugins.GPOS
	case schema.HINFO:
		return plugins.HINFO
	case schema.HIP:
		return plugins.HIP
	case schema.HTTPS:
		return plugins.HTTPS
	case schema.IPSECKEY:
		return plugins.IPSECKEY
	case schema.ISDN:
		return plugins.ISDN
	case schema.IXFR:
		return plugins.IXFR
	case schema.KEY:
		return plugins.KEY
	case schema.KX:
		return plugins.KX
	case schema.L32:
		return plugins.L32
	case schema.L64:
		return plugins.L64
	case schema.LOC:
		return plugins.LOC
	case schema.LP:
		return plugins.LP
	case schema.MAILA:
		return plugins.MAILA
	case schema.MAILB:
		return plugins.MAILB
	case schema.MB:
		return plugins.MB
	case schema.MD:
		return plugins.MD
	case schema.MF:
		return plugins.MF
	case schema.MG:
		return plugins.MG
	case schema.MINFO:
		return plugins.MINFO
	case schema.MR:
		return plugins.MR
	case schema.MX:
		return plugins.MX
	case schema.NAPTR:
		return plugins.NAPTR
	case schema.NB:
		return plugins.NB
	case schema.NBSTAT:
		return plugins.NBSTAT
	case schema.NID:
		return plugins.NID
	case schema.NIMLOC:
		return plugins.NIMLOC
	case schema.NINFO:
		return plugins.NINFO
	case schema.NS:
		return plugins.NS
	case schema.NSAP:
		return plugins.NSAP
	case schema.NSAP_PTR:
		return plugins.NSAP_PTR
	case schema.NSEC:
		return plugins.NSEC
	case schema.NSEC3:
		return plugins.NSEC3
	case schema.NSEC3PARAM:
		return plugins.NSEC3PARAM
	case schema.NULL:
		return plugins.NULL
	case schema.NXT:
		return plugins.NXT
	case schema.OPENPGPKEY:
		return plugins.OPENPGPKEY
	case schema.OPT:
		return plugins.OPT
	case schema.PTR:
		return plugins.PTR
	case schema.PX:
		return plugins.PX
	case schema.RKEY:
		return plugins.RKEY
	case schema.RP:
		return plugins.RP
	case schema.RT:
		return plugins.RT
	case schema.RRSIG:
		return plugins.RRSIG
	case schema.SIG:
		return plugins.SIG
	case schema.SINK:
		return plugins.SINK
	case schema.SMIMEA:
		return plugins.SMIMEA
	case schema.SOA:
		return plugins.SOA
	case schema.SPF:
		return plugins.SPF
	case schema.SRV:
		return plugins.SRV
	case schema.SSHFP:
		return plugins.SSHFP
	case schema.SVCB:
		return plugins.SVCB
	case schema.TA:
		return plugins.TA
	case schema.TALINK:
		return plugins.TALINK
	case schema.TKEY:
		return plugins.TKEY
	case schema.TLSA:
		return plugins.TLSA
	case schema.TSIG:
		return plugins.TSIG
	case schema.TXT:
		return plugins.TXT
	case schema.UID:
		return plugins.UID
	case schema.UINFO:
		return plugins.UINFO
	case schema.UNSPEC:
		return plugins.UNSPEC
	case schema.URI:
		return plugins.URI
	case schema.WKS:
		return plugins.WKS
	case schema.X25:
		return plugins.X25
	case schema.ZONEMD:
		return plugins.ZONEMD
	default:
		return UNKNOWN
	}
}

func ResourceRecordType(t plugins.PluginType) schema.ResourceRecordType {
	switch t {
	case plugins.A:
		return schema.A
	case plugins.A6:
		return schema.A6
	case plugins.AAAA:
		return schema.AAAA
	case plugins.AFSDB:
		return schema.AFSDB
	case plugins.ALIAS:
		return schema.ALIAS
	case plugins.ANAME:
		return schema.ANAME
	case plugins.APL:
		return schema.APL
	case plugins.ATMA:
		return schema.ATMA
	case plugins.AXFR:
		return schema.AXFR
	case plugins.CAA:
		return schema.CAA
	case plugins.CDNSKEY:
		return schema.CDNSKEY
	case plugins.CDS:
		return schema.CDS
	case plugins.CERT:
		return schema.CERT
	case plugins.CNAME:
		return schema.CNAME
	case plugins.CSYNC:
		return schema.CSYNC
	case plugins.DHCID:
		return schema.DHCID
	case plugins.DLV:
		return schema.DLV
	case plugins.DNAME:
		return schema.DNAME
	case plugins.DNSKEY:
		return schema.DNSKEY
	case plugins.DOA:
		return schema.DOA
	case plugins.DS:
		return schema.DS
	case plugins.EID:
		return schema.EID
	case plugins.EUI48:
		return schema.EUI48
	case plugins.EUI64:
		return schema.EUI64
	case plugins.GID:
		return schema.GID
	case plugins.GPOS:
		return schema.GPOS
	case plugins.HINFO:
		return schema.HINFO
	case plugins.HIP:
		return schema.HIP
	case plugins.HTTPS:
		return schema.HTTPS
	case plugins.IPSECKEY:
		return schema.IPSECKEY
	case plugins.ISDN:
		return schema.ISDN
	case plugins.IXFR:
		return schema.IXFR
	case plugins.KEY:
		return schema.KEY
	case plugins.KX:
		return schema.KX
	case plugins.L32:
		return schema.L32
	case plugins.L64:
		return schema.L64
	case plugins.LOC:
		return schema.LOC
	case plugins.LP:
		return schema.LP
	case plugins.MAILA:
		return schema.MAILA
	case plugins.MAILB:
		return schema.MAILB
	case plugins.MB:
		return schema.MB
	case plugins.MD:
		return schema.MD
	case plugins.MF:
		return schema.MF
	case plugins.MG:
		return schema.MG
	case plugins.MINFO:
		return schema.MINFO
	case plugins.MR:
		return schema.MR
	case plugins.MX:
		return schema.MX
	case plugins.NAPTR:
		return schema.NAPTR
	case plugins.NB:
		return schema.NB
	case plugins.NBSTAT:
		return schema.NBSTAT
	case plugins.NID:
		return schema.NID
	case plugins.NIMLOC:
		return schema.NIMLOC
	case plugins.NINFO:
		return schema.NINFO
	case plugins.NS:
		return schema.NS
	case plugins.NSAP:
		return schema.NSAP
	case plugins.NSAP_PTR:
		return schema.NSAP_PTR
	case plugins.NSEC:
		return schema.NSEC
	case plugins.NSEC3:
		return schema.NSEC3
	case plugins.NSEC3PARAM:
		return schema.NSEC3PARAM
	case plugins.NULL:
		return schema.NULL
	case plugins.NXT:
		return schema.NXT
	case plugins.OPENPGPKEY:
		return schema.OPENPGPKEY
	case plugins.OPT:
		return schema.OPT
	case plugins.PTR:
		return schema.PTR
	case plugins.PX:
		return schema.PX
	case plugins.RKEY:
		return schema.RKEY
	case plugins.RP:
		return schema.RP
	case plugins.RT:
		return schema.RT
	case plugins.RRSIG:
		return schema.RRSIG
	case plugins.SIG:
		return schema.SIG
	case plugins.SINK:
		return schema.SINK
	case plugins.SMIMEA:
		return schema.SMIMEA
	case plugins.SOA:
		return schema.SOA
	case plugins.SPF:
		return schema.SPF
	case plugins.SRV:
		return schema.SRV
	case plugins.SSHFP:
		return schema.SSHFP
	case plugins.SVCB:
		return schema.SVCB
	case plugins.TA:
		return schema.TA
	case plugins.TALINK:
		return schema.TALINK
	case plugins.TKEY:
		return schema.TKEY
	case plugins.TLSA:
		return schema.TLSA
	case plugins.TSIG:
		return schema.TSIG
	case plugins.TXT:
		return schema.TXT
	case plugins.UID:
		return schema.UID
	case plugins.UINFO:
		return schema.UINFO
	case plugins.UNSPEC:
		return schema.UNSPEC
	case plugins.URI:
		return schema.URI
	case plugins.WKS:
		return schema.WKS
	case plugins.X25:
		return schema.X25
	case plugins.ZONEMD:
		return schema.ZONEMD
	default:
		return UNKNOWN
	}
}
