name: Zonemgr CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make install-deps

    - name: Tidy
      run: make tidy

    - name: Lint
      run: make lint

    - name: Test
      run: make run-test-with-coverage
      
    - name: Build  
      run: make build-all
